indian_beaches = [
    "Agatti Beach, Lakshadweep",
    "Aksa Beach, Mumbai",
    "Alappuzha Beach, Kerala",
    "Alleppey Beach, Kerala",
    "Anjuna Beach, Goa",
    "Arossim Beach, Goa",
    "Ashwem Beach, Goa",
    "Auroville Beach, Tamil Nadu",
    "Azhimala Beach, Kerala",
    "Baga Beach, Goa",
    "Bangalore Beach, Karnataka",
    "Bangaram Beach, Lakshadweep",
    "Bekal Beach, Kerala",
    "Benaulim Beach, Goa",
    "Betalbatim Beach, Goa",
    "Bordi Beach, Maharashtra",
    "Byndoor Beach, Karnataka",
    "Calangute Beach, Goa",
    "Cherai Beach, Kerala",
    "Chowpatty Beach, Mumbai",
    "Colva Beach, Goa",
    "Dadar Beach, Mumbai",
    "Daman Beach, Daman and Diu",
    "Digha Beach, West Bengal",
    "Diveagar Beach, Maharashtra",
    "Diu Beach, Diu",
    "Dona Paula Beach, Goa",
    "Gokarna Beach, Karnataka",
    "Gopalpur Beach, Odisha",
    "Gorai Beach, Mumbai",
    "Half Moon Beach, Karnataka",
    "Harmal Beach, Goa",
    "Harihareshwar Beach, Maharashtra",
    "Havelock Beach, Andaman Islands",
    "Jampore Beach, Daman and Diu",
    "Juhu Beach, Mumbai",
    "Kadalundi Beach, Kerala",
    "Kalapeni Beach, Lakshadweep",
    "Kappad Beach, Kerala",
    "Kappil Beach, Kerala",
    "Kihim Beach, Maharashtra",
    "Kollam Beach, Kerala",
    "Kozhikode Beach, Kerala",
    "Kovalam Beach, Kerala",
    "Kovalam Beach, Tamil Nadu",
    "Kudle Beach, Karnataka",
    "Kunkeshwar Beach, Maharashtra",
    "Kundapura Beach, Karnataka",
    "Majorda Beach, Goa",
    "Mahabalipuram Beach, Tamil Nadu",
    "Malpe Beach, Karnataka",
    "Malgund Beach, Maharashtra",
    "Mandarmani Beach, West Bengal",
    "Manori Beach, Mumbai",
    "Mararikulam Beach, Kerala",
    "Marari Beach, Kerala",
    "Maravanthe Beach, Karnataka",
    "Marina Beach, Chennai",
    "Marmagao Beach, Goa",
    "Mazhappilangad Beach, Kerala",
    "Murud Beach, Maharashtra",
    "Muzhappilangad Beach, Kerala",
    "Nagaon Beach, Maharashtra",
    "Nagoa Beach, Daman",
    "Nagoa Beach, Diu",
    "Navi Mumbai Beach, Navi Mumbai",
    "Om Beach, Karnataka",
    "Palolem Beach, Goa",
    "Paradise Beach, Karnataka",
    "Radhanagar Beach, Andaman Islands",
    "Rishikonda Beach, Andhra Pradesh",
    "Sasthamkotta Beach, Kerala",
    "Shankarpur Beach, West Bengal",
    "Sinquerim Beach, Goa",
    "Tajpur Beach, West Bengal",
    "Tarkarli Beach, Maharashtra",
    "Thiruvananthapuram Beach, Kerala",
    "Tithal Beach, Gujarat",
    "Varkala Beach, Kerala",
    "Velas Beach, Maharashtra",
    "Velsao Beach, Goa",
    "Vengurla Beach, Maharashtra",
    "Versova Beach, Mumbai"
]
